# Generated by Django 4.1.1 on 2022-09-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
